//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCyberGame.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP
    {
        public string MaA { get; set; }
        public string TenA { get; set; }
        public string LoaiA { get; set; }
        public string DuongDan { get; set; }
        public string HinhAnh { get; set; }
    }
}
