//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCyberGame.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public string MaHD { get; set; }
        public System.DateTime NgayGD { get; set; }
        public string PhuongThucGD { get; set; }
        public double TongTien { get; set; }
        public bool IsCheck { get; set; }
        public string MaTK { get; set; }
        public string MaQTV { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual QUANTRI QUANTRI { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
