//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCyberGame.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CyberGameEntities : DbContext
    {
        public CyberGameEntities()
            : base("name=CyberGameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DICHVU> DICHVUs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<KHACH> KHACHes { get; set; }
        public DbSet<LOAIMAY> LOAIMAYs { get; set; }
        public DbSet<MAY> MAYs { get; set; }
        public DbSet<QUANTRI> QUANTRIs { get; set; }
        public DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
    }
}
