//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCyberGame.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANTRI
    {
        public QUANTRI()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MaQTV { get; set; }
        public string TenQTV { get; set; }
        public string TaiKhoanQT { get; set; }
        public string MatKhauQT { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
