//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCyberGameClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAY
    {
        public string MaM { get; set; }
        public int SoMay { get; set; }
        public int TinhTrang { get; set; }
        public Nullable<double> ThoiGianSD { get; set; }
        public string MaTK { get; set; }
        public string MaLM { get; set; }
    
        public virtual LOAIMAY LOAIMAY { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
