//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCyberGameClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public TAIKHOAN()
        {
            this.MAYs = new HashSet<MAY>();
        }
    
        public string MaTK { get; set; }
        public string TaiKhoan1 { get; set; }
        public string MatKhau { get; set; }
        public string GioChoi { get; set; }
        public string MaKH { get; set; }
    
        public virtual KHACH KHACH { get; set; }
        public virtual ICollection<MAY> MAYs { get; set; }
    }
}
